Migrate from `moment` to `date-fns`
cara-care/dashboard pull request #30
Opened 2020-10-03 17:54 UTC by bengry

## Description
Moment.js has recently [entered maintenance mode](https://momentjs.com/docs/#/-project-status/), and replacing it in this project has been a long-ish standing issue (#11). This PR aims to replace `moment` with `date-fns` completely, with everything that's under this project's direct control.

**Does this PR introduces a breaking change?**
No

### Related Issues
Fixes #10.

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).

2020-10-04 12:58 UTC, bengry commented
I have read the CLA Document and I hereby sign the CLA

2020-10-04 12:59 UTC, bengry commented
recheckcla

2020-10-05 10:21 UTC, janczizikow commented on package.json
> +    "@date-io/date-fns": "^2.10.6",
According to the material-ui pickers [docs](https://material-ui-pickers.dev/getting-started/installation#peer-library), `@date-io/date-fns` should be **v1**

2020-10-05 10:31 UTC, janczizikow requested changes
Hey @bengry thanks a lot for the contribution! 

I've noticed that the app crashes when opening a date-picker, it might be something related to using a different version @date-io adapters (see the comment 👆). You can also try test the app while developing using this url: `https://localhost:3000/export/pPEbU07DVOpWNBRMMuA0fyMWgwzppHfEZ`. Or run you can run e2e tests: `yarn test:e2e` (dashboard test suite)

2020-10-05 10:38 UTC, janczizikow commented
Also don't worry about the CLA & failing checks something is wrong with the github workflow files :)

2020-10-07 13:21 UTC, bengry commented
> Hey @bengry thanks a lot for the contribution!
> 
> I've noticed that the app crashes when opening a date-picker, it might be something related to using a different version @date-io adapters (see the comment 👆). You can also try testing the app while developing using this url: `https://localhost:3000/export/pPEbU07DVOpWNBRMMuA0fyMWgwzppHfEZ`. Or run you can run e2e tests: `yarn test:e2e` (dashboard test suite)

I'll take a look this weekend and fix it, thanks for adding the label in the meantime though!

2020-10-10 07:08 UTC, bengry commented
> I've noticed that the app crashes when opening a date-picker, it might be something related to using a different version @date-io adapters (see the comment 👆). You can also try testing the app while developing using this url: `https://localhost:3000/export/pPEbU07DVOpWNBRMMuA0fyMWgwzppHfEZ`. Or run you can run e2e tests: `yarn test:e2e` (dashboard test suite)

Should be fixed in the latest revision I just pushed. App no longer crashed, and the date pickers work as expected as far as I can tell.

I also ran the E2E tests, all passed except for "should login an existing nutri user" (`nutri` spec file). That's because of bad credentials though, which make sense - since I don't have `CYPRESS_username` or `CYPRESS_password` set up locally, and it seems like the request is going to a real server to rest things out (and not a fixture).

2020-10-10 19:22 UTC, janczizikow approved these changes
LGTM 🎉

2020-10-10 19:34 UTC, merged